# **Data Loading**

In [1]:
import pandas as pd

In [2]:
mutation = pd.read_csv('OmicsSomaticMutations.csv')
expression = pd.read_csv('OmicsExpressionProteinCodingGenesTPMLogp1.csv')
info = pd.read_csv('Model.csv')

/var/folders/r9/tk3nsgjj4_j4z3n_rxsd7s580000gn/T/ipykernel_83041/3459925936.py:1: DtypeWarning: Columns (22,50,56,57,58,59,61) have mixed types. Specify dtype option on import or set low_memory=False.
  mutation = pd.read_csv('OmicsSomaticMutations.csv')

In [3]:
expression = expression.rename(columns={'Unnamed: 0': 'ModelID'})

In [4]:
mutation = mutation[mutation.HugoSymbol == 'TP53'] # filter for TP53 mutations

In [5]:
expression['Mutation'] = expression['ModelID'].isin(mutation['ModelID']).astype(int) 
# here we only consider whether there is mutation or not, maybe include other stuff later

## EDA

In [8]:
expression.head()

,ModelID,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),...,H3C3 (8352),AC098582.1 (8916),DUS4L-BCAP29 (115253422),C8orf44-SGK3 (100533105),ELOA3B (728929),NPBWR1 (2831),ELOA3D (100506888),ELOA3 (162699),CDR1 (1038),Mutation
0,ACH-001113,4.331992,0.000000,7.364660,2.792855,4.471187,0.028569,1.226509,3.044394,6.500005,...,0.189034,0.201634,2.130931,0.555816,0.0,0.275007,0.0,0.0,0.000000,1
1,ACH-001289,4.567424,0.584963,7.106641,2.543496,3.504620,0.000000,0.189034,3.813525,4.221877,...,1.049631,0.321928,1.464668,0.632268,0.0,0.014355,0.0,0.0,0.000000,0
2,ACH-001339,3.150560,0.000000,7.379118,2.333424,4.228049,0.056584,1.310340,6.687201,3.682573,...,1.097611,0.831877,2.946731,0.475085,0.0,0.084064,0.0,0.0,0.042644,1
3,ACH-001979,4.240314,0.000000,5.681168,2.063503,1.641546,0.000000,7.236301,5.948367,4.596935,...,0.000000,0.847997,1.887525,0.176323,0.0,0.000000,0.0,0.0,0.000000,0
4,ACH-002438,4.032101,0.000000,6.674687,2.117695,3.003602,0.000000,2.169925,6.838195,3.253989,...,0.378512,0.584963,1.748461,0.839960,0.0,0.014355,0.0,0.0,0.042644,0

In [12]:
expression.describe()

,TSPAN6 (7105),TNMD (64102),DPM1 (8813),SCYL3 (57147),C1orf112 (55732),FGR (2268),CFH (3075),FUCA2 (2519),GCLC (2729),NFYA (4800),...,H3C3 (8352),AC098582.1 (8916),DUS4L-BCAP29 (115253422),C8orf44-SGK3 (100533105),ELOA3B (728929),NPBWR1 (2831),ELOA3D (100506888),ELOA3 (162699),CDR1 (1038),Mutation
count,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,...,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000,1673.000000
mean,3.364755,0.084035,6.511230,2.351832,3.621073,0.431686,2.231446,5.104079,4.561802,4.005777,...,0.750993,0.491338,2.059848,0.405048,0.016839,0.264674,0.017209,0.023767,0.063297,0.589360
std,1.646095,0.421914,0.650400,0.544043,0.834547,1.216362,2.303087,1.840251,1.149210,0.759120,...,0.777924,0.375643,0.686985,0.367234,0.052869,0.592130,0.060571,0.078146,0.184181,0.492097
min,0.000000,0.000000,3.117695,0.594549,0.056584,0.000000,0.000000,0.000000,1.157044,0.815575,...,0.000000,0.000000,0.263034,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.873813,0.000000,6.104127,1.992768,3.158660,0.014355,0.124328,4.657640,3.855990,3.529821,...,0.000000,0.214125,1.580145,0.124328,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.808385,0.000000,6.503190,2.327687,3.704872,0.042644,1.321928,5.653920,4.463361,3.996389,...,0.555816,0.422233,2.017922,0.333424,0.000000,0.014355,0.000000,0.000000,0.000000,1.000000
75%,4.426936,0.000000,6.928370,2.653060,4.165108,0.150560,4.099295,6.275380,5.190615,4.466627,...,1.195348,0.687061,2.503349,0.594549,0.000000,0.189034,0.000000,0.014355,0.000000,1.000000
max,8.132680,7.814422,9.175250,4.747387,5.972463,8.014299,9.693016,8.633068,9.581991,7.434211,...,4.894818,3.109361,4.433627,2.247928,0.622930,4.254745,0.992768,1.056584,1.867896,1.000000

In [13]:

#check for null values
expression.isnull().sum().sum()

0

In [15]:
#check if data need to be balanced
expression['Mutation'].value_counts()

Mutation
1    986
0    687
Name: count, dtype: int64

In [16]:
# separate in 2 different dataframes based on mutated (1) and not mutated (0) cell lines
mutated = expression[expression['Mutation'] == 1]
not_mutated = expression[expression['Mutation'] == 0]

In [17]:
mutated.shape, not_mutated.shape

((986, 19195), (687, 19195))

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import gseapy as gp
import re

19194

In [ ]:
def prepare_ranked_gene_list(mutated_df, non_mutated_df, gene_cols):
    """
    Calculate differential expression between mutated and non-mutated samples
    and prepare a ranked gene list for GSEA prerank
    """
    # Calculate mean expression for each gene in both groups
    mutated_means = mutated_df[gene_cols].mean()
    non_mutated_means = non_mutated_df[gene_cols].mean()
    
    # Calculate log2 fold change
    # Since TPM values are already log2 transformed, fold change is the difference
    log2fc = mutated_means - non_mutated_means
    
    # Perform t-test for each gene
    pvals = []
    for gene in gene_cols:
        t_stat, p_val = stats.ttest_ind(
            mutated_df[gene].dropna(),
            non_mutated_df[gene].dropna(),
            equal_var=False  # Welch's t-test
        )
        pvals.append(p_val)
    
    # Create a dataframe with results
    result_df = pd.DataFrame({
        'gene': gene_cols,
        'log2fc': log2fc.values,
        'pval': pvals
    })
    
    # Adjust p-values
    result_df['padj'] = stats.false_discovery_rate_control(result_df['pval'])
    
    # Create ranking metric (can use different strategies)
    result_df['ranking'] = result_df['log2fc']
    
    
    # Sort by ranking
    result_df = result_df.sort_values('ranking', ascending=False)
    
    return result_df

vedere se target genes sono nel top o bottom della correlazione

In [46]:
import pandas as pd
from scipy.stats import ttest_ind

# Set ModelID as index if needed
expression = expression.set_index('ModelID')

# Ensure all expression columns are numeric (exclude 'Mutation')
expression_clean = expression.copy()
expression_clean.iloc[:, :-1] = expression_clean.iloc[:, :-1].apply(pd.to_numeric, errors='coerce')

# Split based on Mutation column
mutated = expression_clean[expression_clean['Mutation'] == 1].drop(columns='Mutation')
not_mutated = expression_clean[expression_clean['Mutation'] == 0].drop(columns='Mutation')

# Perform t-test across genes
t_stat, p_val = ttest_ind(mutated.T, not_mutated.T, axis=1, equal_var=False)

# Extract gene names (columns of expression data)
gene_names = mutated.columns.to_list()

# Rank genes by t-statistics
ranks = pd.Series(t_stat, index=gene_names).sort_values(ascending=False)

In [47]:
# Extract Entrez ID or gene symbol
ranks.index = ranks.index.str.extract(r'([A-Z0-9\-]+)')[0]

In [50]:
import gseapy as gp

# Run preranked GSEA
pre_res = gp.prerank(
    rnk=ranks,
    gene_sets='HALLMARK_APOPTOSIS.v2024.1.Hs.gmt',  # or your own .gmt file
    processes=4,
    permutation_num=1000,
    outdir='gsea_results',
    seed=42
)

/var/folders/r9/tk3nsgjj4_j4z3n_rxsd7s580000gn/T/ipykernel_50194/3316381779.py:4: DeprecationWarning: processes is deprecated; use threads
  pre_res = gp.prerank(
2025-05-06 11:03:51,340 [WARNING] Duplicated values found in preranked stats: 0.05% of genes
The order of those genes will be arbitrary, which may produce unexpected results.

In [63]:
# View top enriched pathways
lead_genes = pre_res.res2d.sort_values('FDR q-val', ascending=True)['Lead_genes'].to_list()
lead_genes = [x.split(';') for x in lead_genes]
lead_genes = [item for sublist in lead_genes for item in sublist]
len(lead_genes)  # Number of unique lead genes

35

In [75]:
res = pre_res.res2d.sort_values('NES', ascending=False)
#print(f"\nTop 10 positively enriched pathways ({gmt}):")
print(res['Term', 'NES', 'p-val', 'FDR q-val'])

#print(f"\nTop 10 negatively enriched pathways ({gmt}):")
print(res['Term', 'NES', 'p-val', 'FDR q-val'])

KeyError: ('Term', 'NES', 'p-val', 'FDR q-val')

The gene set HALLMARK_APOPTOSIS shows significant negative enrichment in the dataset, with a normalized enrichment score (NES) of -1.539, and both the nominal p-value and FDR adjusted p-value equal to 0.000, indicating a statistically robust result. The enrichment curve demonstrates that genes associated with apoptosis are predominantly found at the lower end of the ranked gene list, suggesting they are more highly expressed in the non-mutated (wild-type) group compared to the mutated group. This implies that the apoptotic pathway may be downregulated in mutated samples, potentially contributing to a survival advantage or resistance to cell death in these cells.

## Co-gene expression

In [81]:
import pandas as pd
import numpy as np

In [7]:
from scipy.stats import pearsonr
expression = expression.set_index('ModelID')
# Calculate the correlation matrix
cor_matrix = expression.corr(method='pearson')

# Threshold the correlation matrix (e.g., |correlation| > 0.7)
threshold = 0.7
adj_matrix = cor_matrix.applymap(lambda x: 1 if abs(x) > threshold else 0)

/var/folders/r9/tk3nsgjj4_j4z3n_rxsd7s580000gn/T/ipykernel_53216/4111258110.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  adj_matrix = cor_matrix.applymap(lambda x: 1 if abs(x) > threshold else 0)

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

# Create a graph where nodes are genes and edges represent co-expression
G = nx.from_pandas_adjacency(adj_matrix)

# Visualize the network (only a subset for clarity)
plt.figure(figsize=(10, 10))
nx.draw(G, with_labels=True, node_size=50, font_size=8, alpha=0.5)
plt.title('Gene Co-expression Network')
plt.show()

In [ ]:
# Calculate degree centrality (most connected genes)
centrality = nx.degree_centrality(G)
sorted_centrality = sorted(centrality.items(), key=lambda x: x[1], reverse=True)

# Top 10 hub genes
top_hub_genes = sorted_centrality[:10]
print("Top 10 hub genes:", top_hub_genes)

In [ ]:
# Compute the module eigengenes (average expression of genes within a module)
module_eigengenes = expr_data.groupby('module').mean()

# Correlate module eigengenes with mutation status
mutation_status = mutation_status.squeeze()  # Ensure it's a 1D array
module_trait_correlations = module_eigengenes.apply(lambda x: x.corr(mutation_status), axis=1)

# Show correlations between modules and mutation status
print(module_trait_correlations)